### ISSUE TITLE
清理工作流程和发布只能获取前面的30个

### ISSUE THREAD

**Issue by 281677160** [ophub/delete-releases-workflows#1]
清理工作流程跟发布获取API方式都有问题啊，只能获取前面的30个，工作流程跟发布的都是，超过30个就获取不了

**Comment by ophub** [comment]
我刚才更新了，增加了自动翻页查找全部结果，你测试下。
我之前仓库没有这么多结果，所以没注意到这点，刚才查看了官方手册，默认每页显示30个，不翻页。官方有参数可以设置每页显示最多100个，可以翻页查询，我根据手册添加了对应的参数，你再试试。

**Comment by 281677160** [comment]
好的，感谢，等我有时间测试一下，哦，还有一个问题，前面忘记说了，就是我没有任何发布的时候，会显示获取不了api而错误停止的，这个我想是不能停止啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月11日(周日) 中午1:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ophub/delete-releases-workflows] 大佬好 (Issue #1)




 
我刚才更新了，增加了自动翻页查找全部结果，你测试下。
 我之前仓库没有这么多结果，所以没注意到这点，刚才查看了官方手册，默认每页显示30个，不翻页。官方有参数可以设置每页显示最多100个，可以翻页查询，我根据手册添加了对应的参数，你再试试。

**Comment by ophub** [comment]
说的有道理，刚更新了下改成了没有就跳过

**Comment by 281677160** [comment]
刚测试了获取API的，我只测试了工作流程的，只能获取前100个，100个后面应该没翻页继续获取了

**Comment by 281677160** [comment]
我测试了一下，github_page="1" 改成2就获取第二页的100个，改成3就获取第三页的100个，获取API的时候能不能看到它的页数？然后获取一次就写入一次到一个文件里面？最后那个文件就是全部页数的总数了

**Comment by ophub** [comment]
你看脚本。

每个循环会判断是否有下一页。如果当前返回长度不足100时说明已经是最后一页了，否则会继续循环下一页。

**Comment by 281677160** [comment]
> 你看脚本。设置默认一页显示100个，从第一页开始查询。
> 
> 每个循环会判断是否有下一页。如果当前返回长度不足100时说明已经是最后一页了，否则会继续循环下一页。

不会继续了，我测试了，改github_page="1" 参数，可以获取第二页或者第三页，就是github_page="2"或者github_page="3"  ，获取的页数跟参数都正确的，可以连接上
我是把你获取数据的   date: .updated_at, id: .id, name: .name  改成 date: .updated_at, id: .id, run_number: .run_number 来测试的，看它的启动号数连接情况，最直观了
![QQ截图20230611162516](https://github.com/ophub/delete-releases-workflows/assets/66651997/771b4818-47bd-4cb6-8f8b-700de8a9b012)

**Comment by ophub** [comment]
你先测我的可以正常删除吧。

你修改要先确定现在是对的，再修改。

**Comment by 281677160** [comment]
> 你先测我的可以正常删除吧。
> 
> 你修改要先确定现在是对的，再修改。

我现在没办法测试删除了，前面2天折腾的时候把工作流都删除完了，现在只能测试您写的获取API的数据，我刚才测试的就是获取API数据，今天早上也是这样测试获取API数据发现最多才能获取30个的，删除也是靠API数据啊，测试它能获取多少个，应该能知道大概的，你现在新修改的API获取下来就是只有100个，没循环获取
我改字段不是为了删除的，就单纯测试获取API的时候的直观性，我直接就知道它能获取到哪个位置

**Comment by 281677160** [comment]
![QQ截图20230611164011](https://github.com/ophub/delete-releases-workflows/assets/66651997/1575ba0e-4d93-45a8-a1d9-03729b40ad3a)

**Comment by ophub** [comment]
https://github.com/ophub/delete-releases-workflows/blob/00040a66a0df7379fe6afa25004b226ab3576ce7/del.sh#L187-L195


https://github.com/ophub/delete-releases-workflows/blob/00040a66a0df7379fe6afa25004b226ab3576ce7/del.sh#L345-L353

**Comment by ophub** [comment]
发下这个多releases的仓库地址

**Comment by 281677160** [comment]
https://github.com/stupidloud/nanopi-openwrt/actions

**Comment by 281677160** [comment]
![QQ截图20230611164435](https://github.com/ophub/delete-releases-workflows/assets/66651997/d5ca7687-d1f8-4d8a-ae32-95839c5bb61c)
这个是我抽你代码获取API的，直接发布出来，然后下载查看

**Comment by 281677160** [comment]
![QQ截图20230611164543](https://github.com/ophub/delete-releases-workflows/assets/66651997/038da0ea-8e1b-4881-ac40-daa95291c467)
有些API本地编译的时候获取不了，我都是事先在这里获取，然后直接在这里下载的，呵呵，这个删除的API就是纯测试用的

**Comment by ophub** [comment]
https://github.com/ophub/delete-releases-workflows/blob/83667ca7549afc2eca915059be51319030022122/del.sh#L36

更新了下，每次查询允许处理100页，每页处理100个，即每次删除最大量为1000个。
超出1000个的分批删除。

`github_max_page="100"`

这个100页的限制也可以自己修改大些，数字越大处理时间越长。无论查询到多少符合删除结果的记录，接口都是一次删除一个，循环删除1000个也得等一会。

**Comment by 281677160** [comment]
> https://github.com/ophub/delete-releases-workflows/blob/83667ca7549afc2eca915059be51319030022122/del.sh#L36-L39
> 
> 更新了下，每次查询允许处理100页，每页处理100个，即每次删除最大量为1000个。 超出1000个的分批删除。
> 
> `github_max_page="100"`
> 
> 这个100页的限制也可以自己修改大些，数字越大处理时间越长。无论查询到多少符合删除结果的记录，github的接口都是一次运行删除一个ID，循环删除1000个也得等一会。

1000个应该足够了，应该很少人会保留这么多的，您在README.md说明一下就好了，这样大家都清楚明白就没问题了，如果1000个要求时间太长的话，建议50页也应该足够

**Comment by 281677160** [comment]
对了，还有个保留工作流程的，我看你是按启动名字的关键词来保留，我感觉这样保留对很多人不适宜，保留启动序列号或者更方便，不过用保留启动号的话，如果是保留多的也麻烦就是，不过我感觉应该没人会保留很多，都是保留关键的或者应该也没啥好保留了，保留启动序列号，就是我上面截图给你看的那个，也就是run_number

**Comment by ophub** [comment]
run_number大家不会看，而且查起来也费劲。
一般需要保留workflows是为了保留某些工件，用构建的工作流名称方便区分，写个关键字就保留了。
